### Libraries

In [152]:
import pandas as pd
import os

### Csv file to data frame

In [153]:
# load dataset
file_name = 'public_emdat_project.csv'
file_path = os.path.abspath(os.path.join(os.getcwd(), file_name))
df = pd.read_csv(file_path, sep=',', encoding='ISO-8859-1')

### Checking a few first rows

In [154]:
df.head()

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,...,Reconstruction Costs ('000 US$),"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,Entry Date,Last Update
0,1999-9388-DJI,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,DJI,...,NaN,NaN,NaN,NaN,NaN,NaN,58.111474,"[{""adm1_code"":1093,""adm1_name"":""Ali Sabieh""},{...",2006-03-01,2023-09-25
1,1999-9388-SDN,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,SDN,...,NaN,NaN,NaN,NaN,NaN,NaN,56.514291,"[{""adm1_code"":2757,""adm1_name"":""Northern Darfu...",2006-03-08,2023-09-25
2,1999-9388-SOM,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,SOM,...,NaN,NaN,NaN,NaN,NaN,NaN,56.514291,"[{""adm1_code"":2691,""adm1_name"":""Bay""},{""adm1_c...",2006-03-08,2023-09-25
3,2000-0001-AGO,No,tec-tra-roa-roa,Technological,Transport,Road,Road,NaN,NaN,AGO,...,NaN,NaN,NaN,NaN,NaN,NaN,56.514291,NaN,2004-10-27,2023-09-25
4,2000-0002-AGO,No,nat-hyd-flo-riv,Natural,Hydrological,Flood,Riverine flood,NaN,NaN,AGO,...,NaN,NaN,NaN,NaN,10000.0,17695.0,56.514291,"[{""adm2_code"":4214,""adm2_name"":""Baia Farta""},{...",2005-02-03,2023-09-25

### Death toll data

In [155]:
df_death = df[['Country','Region', 'Total Deaths', 'Event Name', 'Start Year', 'End Year', 'Disaster Group', 'Disaster Type']]
df_death.head()

,Country,Region,Total Deaths,Event Name,Start Year,End Year,Disaster Group,Disaster Type
0,Djibouti,Africa,NaN,NaN,2001,2001,Natural,Drought
1,Sudan,Africa,NaN,NaN,2000,2001,Natural,Drought
2,Somalia,Africa,21.0,NaN,2000,2001,Natural,Drought
3,Angola,Africa,14.0,NaN,2000,2000,Technological,Road
4,Angola,Africa,31.0,NaN,2000,2000,Natural,Flood

### The most deadly disaster

In [156]:
df_death.loc[[df_death['Total Deaths'].idxmax()]]

,Country,Region,Total Deaths,Event Name,Start Year,End Year,Disaster Group,Disaster Type
7663,Haiti,Americas,222570.0,NaN,2010,2010,Natural,Earthquake

### Additional libraries

In [157]:
import plotly.express as px

### Death toll by country

In [158]:
df_dtoll_by_country = df.groupby('Country')['Total Deaths'].sum().sort_values(ascending=False)
df_dtoll_by_country

Country
Haiti                        241207.0
Indonesia                    196343.0
Myanmar                      141286.0
China                        133988.0
India                        102593.0
                               ...
Isle of Man                       0.0
Cook Islands                      0.0
Wallis and Futuna Islands         0.0
Saint Kitts and Nevis             0.0
Iceland                           0.0
Name: Total Deaths, Length: 222, dtype: float64

In [159]:
df_dtoll_by_country_filtered = df_dtoll_by_country[df_dtoll_by_country > 10000]
df_dtoll_by_country_filtered

Country
Haiti                               241207.0
Indonesia                           196343.0
Myanmar                             141286.0
China                               133988.0
India                               102593.0
Pakistan                             92445.0
Russian Federation                   63045.0
Türkiye                              55248.0
Italy                                41644.0
Sri Lanka                            38228.0
Iran (Islamic Republic of)           33755.0
France                               33173.0
Philippines                          30118.0
Nigeria                              27587.0
Spain                                27467.0
Somalia                              24749.0
Democratic Republic of the Congo     24293.0
Japan                                23768.0
Bangladesh                           19672.0
Afghanistan                          18232.0
Germany                              18209.0
Libya                                17457.0
Nepal                                16326.0
Thailand                             12178.0
United States of America             11311.0
Name: Total Deaths, dtype: float64

In [160]:
df_dtoll_by_country_filtered.to_csv(os.path.join(os.getcwd(),'CSV_files_for_dashboard','dtoll_by_country.csv'))

In [161]:

dtoll_by_country_plot = px.bar(df_dtoll_by_country_filtered, 
                               x=df_dtoll_by_country_filtered.index, 
                               y=df_dtoll_by_country_filtered.values, 
                               labels={'x':'Country', 'y':'Total Deaths'}, 
                               title="Total Deaths by Country (> 10000)")
dtoll_by_country_plot.update_layout(title_x=0.5, title_font=dict(size=25))
dtoll_by_country_plot.show()

### Death toll by region

In [162]:
df_dtoll_by_region = df.groupby('Region')['Total Deaths'].sum().sort_values(ascending=False)
df_dtoll_by_region

Region
Asia        953831.0
Americas    299746.0
Europe      232255.0
Africa      231059.0
Oceania       3896.0
Name: Total Deaths, dtype: float64

In [163]:
df_dtoll_by_region.to_csv(os.path.join(os.getcwd(),'CSV_files_for_dashboard', 'dtoll_by_region.csv'))

In [164]:
dtoll_by_region_plot = px.bar(df_dtoll_by_region, 
                              x=df_dtoll_by_region.index, 
                              y=df_dtoll_by_region.values,
                              labels={'x':'Region', 'y':'Total Deaths'},
                              title="Total Deaths by Region")
dtoll_by_region_plot.update_layout(title_x=0.5, title_font=dict(size=25))
dtoll_by_region_plot.show()

### Death toll by disaster group and type

Total number of deaths by disaster group

In [165]:
df_dtoll_by_disaster_grp = df.groupby('Disaster Group')['Total Deaths'].sum().sort_values(ascending=False)
df_dtoll_by_disaster_grp

Disaster Group
Natural          1545189.0
Technological     175598.0
Name: Total Deaths, dtype: float64

Total number of deaths by disaster type with more than 1000 victims

In [166]:
# Grouping data to get casualty totals for each type of disaster
df_dtoll_by_disaster_tp = df.groupby('Disaster Type')['Total Deaths'].sum().sort_values(ascending=False)

# Filltered data with more than 1000 victims
df_dtoll_by_disaster_tp_filtered = df_dtoll_by_disaster_tp[df_dtoll_by_disaster_tp > 1000]

# Check created frame
df_dtoll_by_disaster_tp_filtered

Disaster Type
Earthquake                          788400.0
Extreme temperature                 237083.0
Storm                               219999.0
Flood                               132190.0
Epidemic                            118149.0
Water                                50336.0
Road                                 45910.0
Drought                              24160.0
Mass movement (wet)                  20140.0
Air                                  16844.0
Explosion (Industrial)               14014.0
Fire (Miscellaneous)                 10511.0
Miscellaneous accident (General)      9188.0
Rail                                  7079.0
Explosion (Miscellaneous)             5524.0
Collapse (Industrial)                 5510.0
Collapse (Miscellaneous)              4491.0
Fire (Industrial)                     2815.0
Wildfire                              2501.0
Industrial accident (General)         2489.0
Volcanic activity                     1734.0
Name: Total Deaths, dtype: float64

In [167]:
# Create bubble chart
fig = px.scatter(
    x=df_dtoll_by_disaster_tp_filtered.index,           
    y=df_dtoll_by_disaster_tp_filtered.values,          
    size=df_dtoll_by_disaster_tp_filtered.values,       
    size_max=60,                   
    labels={'x': 'Disaster Type', 'y': 'Total Deaths'},  
    title="Total Deaths by Disaster Type (Above 1000 Deaths)"
)

# Add visual settings
fig.update_traces(marker=dict(opacity=0.7, line=dict(width=2, color='DarkSlateGrey')))
fig.update_layout(xaxis_title="Disaster Type", yaxis_title="Total Deaths")

# Display the graph
fig.show()

In [168]:
# Grouping data to get casualty totals for each type of disaster and year
df_disasters_by_year_type = df.groupby(['Start Year', 'Disaster Type'])['Total Deaths'].sum().reset_index()

# Filtering results to include only disasters with more than 1,000 victims, excluding year 2024
df_filtered = df_disasters_by_year_type[(df_disasters_by_year_type['Total Deaths'] > 1000) &
                                        (df_disasters_by_year_type['Start Year'] != 2024)]

# Create a line graph
fig = px.line(
    df_filtered,
    x='Start Year',            
    y='Total Deaths',           
    color='Disaster Type',      
    labels={'Start Year': 'Year', 'Total Deaths': 'Total Deaths'},  
    title="Total Deaths by Disaster Type Over Years (Above 1000 Deaths)"
)

# Adjusting the X axis to show each year
fig.update_xaxes(dtick=1)

# Display the graph
fig.show()

### Number of disasters over years

In [169]:
df_disasters_over_years = df.groupby('Start Year')['DisNo.'].count()
# removing data from 2024 as it is not complete
df_disasters_over_years = df_disasters_over_years[df_disasters_over_years.index != 2024]

df_disasters_over_years.to_csv(os.path.join(os.getcwd(),'CSV_files_for_dashboard','disasters_over_years.csv'))

In [170]:
distasters_over_years_plot = px.bar(df_disasters_over_years, 
                                    x=df_disasters_over_years.index, 
                                    y=df_disasters_over_years.values,
                                    title='Number of disasters over years',
                                    labels={'x':'Year', 'y':'Number of disasters'})
distasters_over_years_plot.update_layout(title_x=0.5, 
                                         title_font=dict(size=25), 
                                         xaxis=dict(tickmode='linear'), 
                                         xaxis_title='Year')
distasters_over_years_plot.show()

### Number of distasters by region by year

In [171]:
df_no_of_disasters_by_region_by_year = df.groupby(['Region', 'Start Year'])['DisNo.'].count().reset_index()

# removing data from 2024 as it is not complete
df_no_of_disasters_by_region_by_year = df_no_of_disasters_by_region_by_year[df_no_of_disasters_by_region_by_year['Start Year'] != 2024]
df_no_of_disasters_by_region_by_year.to_csv(os.path.join(os.getcwd(),'CSV_files_for_dashboard','no_of_disasters_by_region_by_year.csv'), index=False)

In [172]:
df_no_of_disasters_by_region_by_year_plot = px.bar(df_no_of_disasters_by_region_by_year,
                                                    x='Start Year',
                                                    y='DisNo.',
                                                    color='Region',
                                                    title='Number of disasters by region and year',
                                                    barmode='group')
df_no_of_disasters_by_region_by_year_plot.update_layout(title_x=0.5, 
                                                        title_font=dict(size=25), 
                                                        xaxis=dict(tickmode='linear'), 
                                                        xaxis_title='Year',
                                                        yaxis_title='Number of disasters')
df_no_of_disasters_by_region_by_year_plot.show()

### Number of disasters by group by year

In [173]:
df_no_of_disasters_by_group_by_year = df.groupby(['Disaster Group', 'Region', 'Start Year'])['DisNo.'].count().reset_index()

# removing data from 2024 as it is not complete
df_no_of_disasters_by_group_by_year = df_no_of_disasters_by_group_by_year[df_no_of_disasters_by_group_by_year['Start Year'] != 2024]
df_no_of_disasters_by_group_by_year.to_csv(os.path.join(os.getcwd(),'CSV_files_for_dashboard','no_of_disasters_by_group_by_year.csv'), index=False)

In [174]:
df_no_of_disasters_by_group_by_year_plot = px.bar(df_no_of_disasters_by_group_by_year,
                                                  x='Start Year',
                                                  y='DisNo.',
                                                  color='Region',
                                                  facet_col='Disaster Group',
                                                  title='Number of disasters by group, region and year',)
df_no_of_disasters_by_group_by_year_plot.update_layout(title_x=0.5, title_font=dict(size=25), yaxis_title='Number of disasters')
df_no_of_disasters_by_group_by_year_plot.update_xaxes(title_text='Year', tickmode='linear')
df_no_of_disasters_by_group_by_year_plot.show()

### The 3 most common disaster types

In [175]:
df_most_common_disaster_type = df.groupby('Disaster Type')['DisNo.'].count().sort_values(ascending=False).reset_index().head(3)
df_most_common_disaster_type.rename(columns={'Disaster Type':'Disaster Type', 'DisNo.':'Disaster Occurences'}, inplace=True)
df_most_common_disaster_type.to_csv(os.path.join(os.getcwd(),'CSV_files_for_dashboard','most_common_disaster_type.csv'), index=False)

### Total Damage by Disaster Type

In [176]:
toll_damage_by_disaster_type = df.groupby(['Disaster Type'])["Total Damage ('000 US$)"].sum().nlargest(10).reset_index()

toll_damage_by_disaster_type.to_csv(os.path.join(os.getcwd(),'CSV_files_for_dashboard','toll_damage_by_disaster_type.csv'))

fig = px.bar(
    toll_damage_by_disaster_type,
    x='Disaster Type',
    y="Total Damage ('000 US$)",
    title='Total Damage by Disaster Type',
    labels={'Total Damage (\'000 US$)': 'Total Damage (‘000 US$)', 'Disaster Type': 'Disaster Type'},
    color_discrete_sequence=['wheat'],  
    width=800,
    height=500
)

fig.update_layout(
    xaxis_title='Disaster Type',
    yaxis_title='Total Damage (‘000 US$)',
    title_font_size=16,
    xaxis_tickangle=-45  
)

fig.show()

### Total Damage by Country

In [177]:
toll_damage_by_country = df.groupby(['Country'])["Total Damage ('000 US$)"].sum().nlargest(10).reset_index()
toll_damage_by_country.to_csv(os.path.join(os.getcwd(),'CSV_files_for_dashboard','toll_damage_by_country.csv'))

fig = px.bar(
    toll_damage_by_country,
    x='Country',
    y="Total Damage ('000 US$)",
    title='Total Damage by Country',
    labels={'Total Damage (\'000 US$)': 'Total Damage (‘000 US$)', 'Country': 'Country'},
    color_discrete_sequence=['tan'],  
    width=800,
    height=500
)

fig.update_layout(
    xaxis_title='Country',
    yaxis_title='Total Damage (‘000 US$)',
    title_font_size=16,
    xaxis_tickangle=-45,  
    legend_title_text='Country', 
    legend=dict(x=1.05, y=1, orientation='v')  
)

fig.show()

### Total Damage by Region

In [178]:
toll_damage_by_region = df.groupby(['Region'])["Total Damage ('000 US$)"].sum().reset_index()
toll_damage_by_region.to_csv(os.path.join(os.getcwd(),'CSV_files_for_dashboard','toll_damage_by_region.csv'))

fig = px.bar(
    toll_damage_by_region,
    x='Region',
    y="Total Damage ('000 US$)",
    title='Total Damage by Region',
    labels={'Total Damage (\'000 US$)': 'Total Damage (‘000 US$)', 'Region': 'Region'},
    color_discrete_sequence=['burlywood'],  
    width=800,
    height=500
)

fig.update_layout(
    xaxis_title='Region',
    yaxis_title='Total Damage (‘000 US$)',
    title_font_size=16,
    xaxis_tickangle=-45,  
    legend_title_text='Region',  
    legend=dict(x=1.05, y=1, orientation='v')  
)

fig.show()

### Country where Most Disasters Occured by Disaster Group

In [179]:
country_most_disasters_occured = df.groupby(['Country', 'Disaster Group'])['DisNo.'].count().unstack(fill_value=0)

top_10_countries = country_most_disasters_occured.sum(axis=1).nlargest(10).index

top_10_disasters_by_type = country_most_disasters_occured.loc[top_10_countries]

top_10_disasters_by_group_country = top_10_disasters_by_type.reset_index().melt(id_vars='Country', var_name='Disaster Group', value_name='Number of Disasters')

top_10_disasters_by_group_country.to_csv(os.path.join(os.getcwd(),'CSV_files_for_dashboard','top_10_disasters_by_group_country.csv'))

fig = px.bar(
    top_10_disasters_by_group_country,
    x='Country',
    y='Number of Disasters',
    color='Disaster Group',
    title='Countries where Most Disasters Occured',
    labels={'Number of Disasters': 'Number of Disasters', 'Country': 'Country', 'Disaster Group': 'Disaster Group'},
    color_discrete_sequence=["darkseagreen", "tan"],  
    width=800,
    height=500
)

fig.update_layout(
    xaxis_title='Country',
    yaxis_title='Number of Disasters',
    title_font_size=16,
    xaxis_tickangle=-45,  
    legend_title_text='Disaster Group', 
    legend=dict(x=1.05, y=1, orientation='v')  
)

fig.show()

### Country where Most Disasters Occured by Disaster Type

In [180]:
country_disasters_by_type = df.groupby(['Country', 'Disaster Type'])['DisNo.'].count().unstack(fill_value=0)

top_10_country_most_disasters_occured_type = country_disasters_by_type.sum(axis=1).nlargest(10).index

top_10_disasters_by_type = country_disasters_by_type.loc[top_10_country_most_disasters_occured_type]

top_10_disasters_by_type_country = top_10_disasters_by_type.reset_index().melt(id_vars='Country', var_name='Disaster Type', value_name='Number of Disasters')

top_10_disasters_by_type_country.to_csv(os.path.join(os.getcwd(),'CSV_files_for_dashboard','top_10_disasters_by_type_country.csv'))

fig = px.bar(
    top_10_disasters_by_type_country,
    x='Country',
    y='Number of Disasters',
    color='Disaster Type',
    title='Countries where Most Disasters Occured',
    labels={'Number of Disasters': 'Number of Disasters', 'Country': 'Country', 'Disaster Type': 'Disaster Type'},
    width=1000,
    height=700
)

fig.update_layout(
    xaxis_title='Country',
    yaxis_title='Number of Disasters',
    title_font_size=16,
    xaxis_tickangle=-45,  
    legend_title_text='Disaster Type',  
    legend=dict(x=1.05, y=1, orientation='v')  
)

fig.show()

### People affected by disaster type

In [181]:
df_total_affected_by_disaster_type = df[['Disaster Type', 'Total Affected']].dropna()

# top 5, because the next 5 distaster types have very different numbers of affected, which makes the bar unreadable

df_total_affected_by_disaster_type.to_csv(os.path.join(os.getcwd(),'CSV_files_for_dashboard','total_affected_by_disaster_type.csv'))


df_total_affected_by_disaster_type = df_total_affected_by_disaster_type.groupby('Disaster Type').sum().astype(int).sort_values(by='Total Affected', ascending=False).head(5).reset_index()

fig = px.bar(
    data_frame = df_total_affected_by_disaster_type,
    x = 'Disaster Type',
    y = 'Total Affected',
    hover_data={
        'Total Affected': True,
        'Disaster Type': False}
)

fig.update_layout(
    plot_bgcolor="#F7F0F5",
    yaxis_title = 'Number of people affected',
    xaxis_title = 'Distaster type',
    yaxis_tickformat=',',
    title={
        'text': 'Total number of people affected by disaster type [top 5 disaster types]', 
        'font': {'size': 20},
        'x': 0.5, 
        'xanchor': 'center', 
        'yanchor': 'top'
    }
)

fig.show()

### Top 5 years with highest number of disasters by disaster group

In [223]:
df_disasters_by_groups_over_years = df.groupby(by = ['Disaster Group', 'Start Year'])['DisNo.'].count().reset_index().sort_values(['Disaster Group', 'DisNo.'], ascending=[True, False]).groupby(by=['Disaster Group']).head(5)
df_disasters_by_groups_over_years = df_disasters_by_groups_over_years.loc[df_disasters_by_groups_over_years['Start Year'] != 2024]

df_disasters_by_groups_over_years.to_csv(os.path.join(os.getcwd(),'CSV_files_for_dashboard','df_disasters_by_groups_over_years.csv'))

df_disasters_by_groups_over_years

   Disaster Group  Start Year  DisNo.
0         Natural        2000     524
2         Natural        2002     505
5         Natural        2005     483
6         Natural        2006     460
7         Natural        2007     447
30  Technological        2005     371
25  Technological        2000     370
27  Technological        2002     360
29  Technological        2004     359
28  Technological        2003     334

In [198]:
fig = px.scatter(df_disasters_by_groups_over_years, 
                 x='Start Year', 
                 y='DisNo.', 
                 size='DisNo.',  
                 color='Disaster Group',
                 title="Top 5 years with highest number of disasters by disaster type group",
                 labels={"DisNo.": "Number of disasters", "Start Year": "Year"})
                 
fig.update_layout(yaxis_title="Disaster Type Group", xaxis_title="Year", title_x=0.5)
fig.show()

### Number of disasters by year and disaster group

In [224]:
df_disasters_by_groups_and_years = df.groupby(by = ['Disaster Group', 'Start Year']).agg(
    DisCount=('DisNo.', 'count'),
    AffectedSum=('Total Affected', 'sum')).reset_index()

df_disasters_by_groups_and_years = df_disasters_by_groups_and_years.loc[df_disasters_by_groups_and_years['Start Year'] != 2024]

df_disasters_by_groups_and_years.to_csv(os.path.join(os.getcwd(),'CSV_files_for_dashboard','df_disasters_by_groups_and_years.csv'))

df_disasters_by_groups_and_years

   Disaster Group  Start Year  DisCount  AffectedSum
0         Natural        2000       524  174226753.0
1         Natural        2001       446  108969264.0
2         Natural        2002       505  659393270.0
3         Natural        2003       420  255091094.0
4         Natural        2004       396  161882854.0
5         Natural        2005       483  160682935.0
6         Natural        2006       460  126303543.0
7         Natural        2007       447  212834312.0
8         Natural        2008       394  221831968.0
9         Natural        2009       389  201789495.0
10        Natural        2010       435  259960790.0
11        Natural        2011       360  212766864.0
12        Natural        2012       372  123476495.0
13        Natural        2013       354   99385853.0
14        Natural        2014       343  142682158.0
15        Natural        2015       403  431845024.0
16        Natural        2016       349  205444618.0
17        Natural        2017       371  104220340.0
18        Natural        2018       335   84058641.0
19        Natural        2019       437  109198643.0
20        Natural        2020       406  103458537.0
21        Natural        2021       440  119116255.0
22        Natural        2022       437  186138747.0
23        Natural        2023       412   94427331.0
25  Technological        2000       370      47974.0
26  Technological        2001       325      53365.0
27  Technological        2002       360      68396.0
28  Technological        2003       334     666637.0
29  Technological        2004       359     306818.0
30  Technological        2005       371     100045.0
31  Technological        2006       300     199370.0
32  Technological        2007       277      48374.0
33  Technological        2008       260      38729.0
34  Technological        2009       231      33398.0
35  Technological        2010       235      36925.0
36  Technological        2011       244      55412.0
37  Technological        2012       189      24449.0
38  Technological        2013       191      21813.0
39  Technological        2014       205     296328.0
40  Technological        2015       203     101962.0
41  Technological        2016       185      28738.0
42  Technological        2017       171      21657.0
43  Technological        2018       162       8191.0
44  Technological        2019       170      23680.0
45  Technological        2020       101     314590.0
46  Technological        2021       151     143633.0
47  Technological        2022       158      34362.0
48  Technological        2023       151      28344.0

In [197]:
fig = px.scatter(df_disasters_by_groups_and_years, 
                 x='Start Year', 
                 y='DisCount', 
                 size='DisCount',  
                 color='Disaster Group',
                 title="Number of disasters by year and disaster type group",
                 labels={"DisCount": "Number of disasters", "Start Year": "Year", "AffectedSum": 'Total number of people affected'},
                 hover_data={'AffectedSum': True})
                 
fig.update_layout(yaxis_title="Disaster Type Group", xaxis_title="Year", title_x=0.5)
fig.show()

### Years with highest distaster numbers by types of disasters

In [225]:
df_disasters_by_types_over_years = df.groupby(by = ['Disaster Type', 'Start Year'])['DisNo.'].count().reset_index().sort_values(['Disaster Type', 'DisNo.'], ascending=[True, False]).groupby(by=['Disaster Type']).head(3)
df_disasters_by_types_over_years = df_disasters_by_types_over_years.loc[df_disasters_by_types_over_years['DisNo.'] > 10] 

df_disasters_by_types_over_years.to_csv(os.path.join(os.getcwd(),'CSV_files_for_dashboard','df_disasters_by_types_over_years.csv'))

df_disasters_by_types_over_years.head()

            Disaster Type  Start Year  DisNo.
0                     Air        2000      31
2                     Air        2002      31
1                     Air        2001      29
59  Collapse (Industrial)        2019      12
54  Collapse (Industrial)        2014      11

In [221]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots


disaster_types = df_disasters_by_types_over_years['Disaster Type'].unique()
num_disasters = len(disaster_types)
cols = 4
rows = (num_disasters // cols) + (num_disasters % cols > 0)  # the second part is to add additional row if num_disasters is not divisible by col

fig = make_subplots(rows=rows, cols=cols, subplot_titles=disaster_types)

for i, disaster in enumerate(disaster_types):
    disaster_data = df_disasters_by_types_over_years[df_disasters_by_types_over_years['Disaster Type'] == disaster]
    
    # we indicate where to draw the plot
    row = (i // cols) + 1
    col = (i % cols) + 1
    
    fig.add_trace(
        go.Scatter(x=disaster_data['Start Year'], y=disaster_data['DisNo.'], mode='markers', name=disaster),
        row=row, col=col
    )

fig.update_layout(height=800, width=1200, title_text="Years with highest distaster numbers by types of disasters", title_x=0.5, showlegend=False)
fig.show()